// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WScoreInfrastructure.Data;

#nullable disable

namespace WScoreInfrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WScoreDomain.Entities.Checkin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<int>("CargaTrabalho")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataCheckin")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("Energia")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Foco")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Humor")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Score")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Sono")
                        .HasColumnType("NUMBER(10)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("RAW(16)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TB_CHECKIN", (string)null);
                });

            modelBuilder.Entity("WScoreDomain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("Id");

                    b.ToTable("TB_USER", (string)null);
                });

            modelBuilder.Entity("WScoreDomain.Entities.Checkin", b =>
                {
                    b.HasOne("WScoreDomain.Entities.User", "User")
                        .WithMany("Checkins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WScoreDomain.Entities.User", b =>
                {
                    b.Navigation("Checkins");
                });
#pragma warning restore 612, 618
        }
    }
}
